CREATE TABLE gym_members (
    member_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name     VARCHAR2(50) NOT NULL,
    last_name      VARCHAR2(50) NOT NULL,
    email          VARCHAR2(100) UNIQUE,
    phone          VARCHAR2(20),
    cnp            VARCHAR2(13),
    join_date      DATE DEFAULT SYSDATE,
    active_flag    CHAR(1) DEFAULT 'Y' CHECK (active_flag IN ('Y','N'))
);

CREATE TABLE gym_trainers (
    trainer_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name     VARCHAR2(50) NOT NULL,
    last_name      VARCHAR2(50) NOT NULL,
    specialty      VARCHAR2(100)
);

CREATE TABLE gym_subscriptions (
    sub_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(50) NOT NULL,
    duration_months NUMBER(2) NOT NULL,
    price           NUMBER(8,2) NOT NULL
);

CREATE TABLE gym_contracts (
    contract_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id      NUMBER NOT NULL REFERENCES gym_members(member_id),
    sub_id         NUMBER NOT NULL REFERENCES gym_subscriptions(sub_id),
    start_date     DATE DEFAULT SYSDATE,
    end_date       DATE,
    status         VARCHAR2(20) CHECK (status IN ('ACTIVE','EXPIRED','CANCELLED'))
);

CREATE TABLE gym_classes (
    class_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR2(100) NOT NULL,
    difficulty     VARCHAR2(20)
                    CHECK (difficulty IN ('BEGINNER','INTERMEDIATE','ADVANCED')),
    trainer_id     NUMBER REFERENCES gym_trainers(trainer_id),
    max_slots      NUMBER(3)
);

CREATE TABLE gym_enrollments (
    enrollment_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id          NUMBER NOT NULL REFERENCES gym_classes(class_id),
    member_id         NUMBER NOT NULL REFERENCES gym_members(member_id),
    enroll_date       DATE DEFAULT SYSDATE,
    attendance_status VARCHAR2(20)
                      CHECK (attendance_status IN ('SCHEDULED','ATTENDED','ABSENT'))
);